### ISSUE TITLE
Can't use direct Github deps on Github Action

### ISSUE THREAD

**Issue by RaphSfeir** [elixir-lang/elixir#11562]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 1.12.3 / OTP 24.1
* Operating system: Github Action environment 

### Current behavior

When using a direct Github link as a dependancy in `mix.exs` like this in my case:
`{:ja_resource, git: "git://github.com/ericdude4/ja_resource.git"}`

`mix deps.get` fails during default Github Action with following error: 

```
mix deps.get
 shell: /usr/bin/bash -e {0}
* Getting ja_resource (git://github.com/ericdude4/ja_resource.git)
fatal: remote error: 
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
** (Mix) Command "git --git-dir=.git fetch --force --quiet --progress" failed
Error: Process completed with exit code 1.
```
My Github action workflow is really the default one created when selecting Elixir preset: 

```
name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: erlef/setup-beam@988e02bfe678367a02564f65ca2e37726dc0268f
      with:
        elixir-version: '1.12.3' # Define the elixir version [required]
        otp-version: '24.1' # Define the OTP version [required]
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      run: mix test

```

### Expected behavior

The deps should be fetched without the fatal error. 
Sorry if this is not the right place to post this but I wasn't sure where to report it.
