### ISSUE TITLE
Mix Formatter not compiling plugins

### ISSUE THREAD

**Issue by TheFirstAvenger** [elixir-lang/elixir#11915]
### Elixir and Erlang/OTP versions

```
Erlang/OTP 24 [erts-12.2.1] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1]
Elixir 1.13.4 (compiled with Erlang/OTP 23)
```

### Operating system

Github Actions CI

### Current behavior

We recently had an issue where we had configured the `HTMLFormatter` as a `plugin` in `.formatter.exs` and it was failing silently in CI.

There are two underlying issues here:

1) When a plugin defined in `.formatter.exs` is not found, `mix format` outputs `Skipping formatter plugin Phoenix.LiveView.HTMLFormatter because module cannot be found` but does not return an error code. This is a problem in CI where the output isn't generally reviewed, only error returns.

2) `mix format` does not compile the application being formatted or its dependencies. This was ok before plugins, but when a plugin is involved, especially if that plugin is not yet compiled, this is a problem.

The combination of these two potentially leaves users in the state of having a Github Actions CI job that performs a checkout and then a `mix format`, which runs without compiling, and then "silently" failed to use the desired plugin.

### Expected behavior

1) `mix format` should fail if a plugin is not found
2) `mix format` should compile the app when a plugin is defined in `.formatter.exs` (maybe only when it is not found?)

**Comment by josevalim** [comment]
We can do option 2 if a plugin is missing but I am not quite sure if we should do option 1 because for some workflows (like editors) formatting something with a warning may be better than not formatting anything at all? But hopefully 2 will address 1?

**Comment by TheFirstAvenger** [comment]
My thoughts on the editor workflows is that personally, I would rather see an error in the editor that formatting failed due to a plugin not being found and be able to fix the issue than to have it silently not run some of the formatting I was expecting and not know why it wasn't formatting correctly.

Maybe if we can't find the plugin, we could run the formatter with what we do have, but still raise an error, that way we get the benefits of both?

**Comment by v0idpwn** [comment]
Had problems with (2) in the past, +1 for ensuring it is compiled when formatting

**Comment by marcandre** [comment]
I'd be inclined to also do 1), i.e. and raise an error and refuse to run, especially until 2) is resolved.

**Comment by johannesE** [comment]
To anyone reading this and looking for a quick fix. Make sure that `mix compile` has been run.

If you are using a ci, here is an example that uses https://github.com/erlef/setup-beam: 
```
      - name: Compile app (required for the formatter plugin)
        run: mix compile
        
      - name: Format with mix format
        run: mix format
        
      - name: Commit mix format code changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "${{ github.event.pusher.name }}"
          author_email: "${{ github.event.pusher.email }}"
          message: 'Fix formatting of elixir code with mix format'
          add: 'lib'
```
