### ISSUE TITLE
generate a .travis.yml when using mix new

### ISSUE THREAD

**Issue by foxnewsnetwork** [elixir-lang/elixir#3890]
Running `mix new` to scaffold a new project is great, but I keep having to drag and drop in a `.travis.yml` config file from the elixir repo if I want to get CI. Would it be a good idea to have `mix new` just spawn a `.travis.yml` file? Something like:

```yaml
language: elixir
elixir: 1.1.1
otp_release:
  - 18.0
sudo: false
before_script:
  - mix deps.get --only test
script:
  - mix test
```

If so, I can do a pr.
